### ISSUE TITLE
libcamera 0.2.0 apt package update breaks picamera2 in virtual environments

### ISSUE THREAD

**Issue by gwvr** [raspberrypi/pylibcamera#1]
## Issue description (regression)

Picamera2 no longer functions in a python virtual environment. I suspect that this is because the pylibcamera PyPI package has not been updated to reflect the changes in libcamera. Picamera2 was working in virtual environments prior to this weeks updates to libcamera.

I have attempted to downgrade libcamera to the previous version, but have been unable to do this because previous versions of some libcamera related apt packages appear to be no longer available from [http://archive.raspberrypi.com/debian].

My use case is that I want to use picamera2 with a Coral Edge TPU on a Raspberry Pi 5. Unfortunately the status of [PyCoral](https://github.com/google-coral/pycoral) is effectively abandonware, and it's not currently usable under Python 3.11 (official builds work on Python 3.9 and [unofficial builds](https://github.com/oberluz/pycoral/releases/tag/2.7.0) work on Python 3.10).

I'd be very grateful if new builds of the appropriate libraries could be made available on PyPI, and would be happy to test these.

## Steps to reproduce error

```bash
sudo apt install virtualenvwrapper
mkvirtualenv --python /usr/bin/python picamera2_system311
workon picamera2_system311
pip install --upgrade pip opencv-python==4.6.0.66 rpi-kms rpi-libcamera picamera2
python picamera2/examples/opencv_face_detect.py
```

Output:
> [2:08:28.411157143] [15215]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
> [2:08:28.423283470] [15221]  INFO RPI pisp.cpp:653 libpisp version v1.0.4 6e3a53d137f4 14-02-2024 (14:00:12)
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  unordered_map::at
> Aborted

## Expected output

```bash
deactivate
python picamera2/examples/opencv_face_detect.py
```
Output:

> [2:09:01.465222100] [15280]  INFO Camera camera_manager.cpp:284 libcamera v0.2.0+46-075b54d5
> [2:09:01.475673597] [15288]  INFO RPI pisp.cpp:662 libpisp version v1.0.4 6e3a53d137f4 14-02-2024 (14:00:12)
> [2:09:01.487437888] [15288]  INFO RPI pisp.cpp:1121 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 to CFE device /dev/media2 and ISP device /dev/media3 using PiSP variant BCM2712_C0
> [2:09:01.489190440] [15280]  INFO Camera camera_manager.cpp:284 libcamera v0.2.0+46-075b54d5
> [2:09:01.503090485] [15291]  INFO RPI pisp.cpp:662 libpisp version v1.0.4 6e3a53d137f4 14-02-2024 (14:00:12)
> [2:09:01.514703350] [15291]  INFO RPI pisp.cpp:1121 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 to CFE device /dev/media2 and ISP device /dev/media3 using PiSP variant BCM2712_C0
> [2:09:01.517895825] [15280]  INFO Camera camera.cpp:1183 configuring streams: (0) 640x480-XRGB8888 (1) 640x480-GBRG16_PISP_COMP1
> [2:09:01.517999880] [15291]  INFO RPI pisp.cpp:1405 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 - Selected sensor format: 640x480-SGBRG10_1X10 - Selected CFE format: 640x480-PC1g
> libpng warning: iCCP: known incorrect sRGB profile

## Package info

```bash
dpkg -l | grep libcamera
```

```
ii  libcamera-apps                       1.4.3-1                             all          transitional package
ii  libcamera-dev:arm64                  0.2.0+rpt20240215-1                 arm64        complex camera support library (development files)
ii  libcamera-ipa:arm64                  0.2.0+rpt20240215-1                 arm64        complex camera support library (IPA modules)
ii  libcamera-tools                      0.2.0+rpt20240215-1                 arm64        complex camera support library (tools)
ii  libcamera0.1:arm64                   0.1.0+rpt20231122-1                 arm64        complex camera support library
ii  libcamera0.2:arm64                   0.2.0+rpt20240215-1                 arm64        complex camera support library
ii  pipewire-libcamera:arm64             0.3.65-3+rpt5+deb12u1               arm64        PipeWire libcamera plugin
ii  python3-libcamera:arm64              0.2.0+rpt20240215-1                 arm64        complex camera support library (Python bindings)
```

```bash
workon picamera2_system311 && pip list
```

```
Package       Version
------------- --------
av            11.0.0
numpy         1.26.4
opencv-python 4.6.0.66
picamera2     0.3.17
pidng         4.0.9
piexif        1.1.3
pillow        10.2.0
pip           24.0
python-prctl  1.8.1
rpi-kms       0.1a1
rpi-libcamera 0.1a2
setuptools    69.0.3
simplejpeg    1.7.2
v4l2-python3  0.3.3
wheel         0.42.0
```

**Comment by will-v-pi** [comment]
Have updated to the latest libcamera release, so should work now - let me know if it does

**Comment by gwvr** [comment]
Thanks @will-v-pi

`pip install rpi-libcamera` results in the following. I can see that commit in the error message corresponds to the libcamera tag that is cloned, but it looks like a version reporting issue?

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting rpi-libcamera
  Using cached rpi_libcamera-0.1a3.tar.gz (9.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup /tmp/pip-install-vg8pli_b/rpi-libcamera_9ccc8fae62a14252ac672cee345d018e /tmp/pip-install-vg8pli_b/rpi-libcamera_9ccc8fae62a14252ac672cee345d018e/.mesonpy-44ztbz1x -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Drevision=v0.2.0+rpt20240215 -Drepository=https://github.com/raspberrypi/libcamera.git -Dversion=v0.2.0+46-075b54d5 --native-file=/tmp/pip-install-vg8pli_b/rpi-libcamera_9ccc8fae62a14252ac672cee345d018e/.mesonpy-44ztbz1x/meson-python-native-file.ini
      The Meson build system
      Version: 1.3.2
      Source dir: /tmp/pip-install-vg8pli_b/rpi-libcamera_9ccc8fae62a14252ac672cee345d018e
      Build dir: /tmp/pip-install-vg8pli_b/rpi-libcamera_9ccc8fae62a14252ac672cee345d018e/.mesonpy-44ztbz1x
      Build type: native build
      Project name: pylibcamera
      Project version: 0.1.0
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Message: Cloning from: https://github.com/raspberrypi/libcamera.git, revision v0.2.0+rpt20240215
      Message: libcamera version is v0.2.0
      
      
      ../meson.build:26:8: ERROR: Problem encountered: This package works with libcamera version v0.2.0+46-075b54d5, but you have version v0.2.0
       installed. Please check the readme for help with this error
      
      A full log can be found at /tmp/pip-install-vg8pli_b/rpi-libcamera_9ccc8fae62a14252ac672cee345d018e/.mesonpy-44ztbz1x/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It's also possible that I've polluted my system by attempting to build libcamera, but I've removed and reinstalled the libcamera apt packages, and the same error persists.

**Comment by will-v-pi** [comment]
It is picking up the wrong libcamera - you can tell by the `libcamera version is v0.2.0` line, which should read `libcamera version is v0.2.0+46-075b54d5`. Have you fully removed your manually built libcamera?

Another check that you're using the correct version of libcamera would be to run `rpicam-hello --version` which should show `libcamera build: v0.2.0+46-075b54d5`

**Comment by gwvr** [comment]
Probably not. I'll attempt to do that next!

I've hacked the pyproject.toml so that the versions match and that enabled pip install of rpi-libcamera. It's functional (although OpenCV support is broken), so that's progress.

`rpicam-hello --version` does show `libcamera build: v0.2.0`, so you're right there.

**Comment by gwvr** [comment]
Having fully removed my manually built libcamera (I note that I hadn't intended to install it system wide, but apparently the build process does that automatically) all seems to be working as expected.

`rpicam-hello --version` now shows `libcamera build: v0.2.0+46-075b54d5` and I'm able to stream from Picamera2 to ffmpeg via OpenCV.

Many thanks for providing the updated PyPI package!

**Comment by gwvr** [comment]
I have tested the updated package with locally compiled Python 3.9, 3.10 & 3.11, and can confirm that picamera2 is functional with all three.

**Comment by Whiteflakes** [comment]
@will-v-pi I think the latest version of libcamera is not supported presently by this package. I got the following error.
```
 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup /tmp/pip-install-v9dvi7sb/rpi-libcamera_76a9210eeb9e43d3990a87c09dbba835 /tmp/pip-install-v9dvi7sb/rpi-libcamera_76a9210eeb9e43d3990a87c09dbba835/.mesonpy-ozzli7h_ -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Drevision=v0.3.1+rpt20240906 -Drepository=https://github.com/raspberrypi/libcamera.git -Dversion=v0.3.1+50-69a894c4 --native-file=/tmp/pip-install-v9dvi7sb/rpi-libcamera_76a9210eeb9e43d3990a87c09dbba835/.mesonpy-ozzli7h_/meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: /tmp/pip-install-v9dvi7sb/rpi-libcamera_76a9210eeb9e43d3990a87c09dbba835
      Build dir: /tmp/pip-install-v9dvi7sb/rpi-libcamera_76a9210eeb9e43d3990a87c09dbba835/.mesonpy-ozzli7h_
      Build type: native build
      Project name: pylibcamera
      Project version: 0.1.0
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Message: Cloning from: https://github.com/raspberrypi/libcamera.git, revision v0.3.1+rpt20240906
      Message: libcamera version is v0.3.2+99-1230f78d
      
      
      ../meson.build:26:8: ERROR: Problem encountered: This package works with libcamera version v0.3.1+50-69a894c4, but you have version v0.3.2+99-1230f78d
       installed. Please check the readme for help with this error
      
      A full log can be found at /tmp/pip-install-v9dvi7sb/rpi-libcamera_76a9210eeb9e43d3990a87c09dbba835/.mesonpy-ozzli7h_/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```
I think the version 3.2 support will solve this.
Any help is much appreciated. Thanks.

**Comment by will-v-pi** [comment]
Yep, I'm adding support for version 3.2 today
